spring.application.name=HenriPank

# Connecting to my database i made
spring.datasource.url=jdbc:postgresql://localhost:5432/HenriPank

# My postgres username
spring.datasource.username=postgres

#postgres password
spring.datasource.password=postgres

#If db table does not exist its automatically created
spring.jpa.hibernate.ddl-auto=update
